spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: first-service
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000

# Настроки ниже нужны для обращения к серверу Eureka
# Но эти настройки вынесены в config-server для
# централизованного хранения и изменения
# eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
# Можно и так:
#      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/